http://localhost:4000/
###
http://localhost:2000/blocks
###
POST http://localhost:4000/blocks

{
    "message": "Mine me!"
}
###


http://localhost:2000/wallet
###

http://localhost:4000/balance/michael?total=true

###
http://localhost:4000/balance/nobod

###
http://localhost:4000/balance/3ba93389769dfe505bcd9950c302155341b48555bae5ca63119d197c90ecddf9860b63f5cf009315223736089522e61f7dec6f23d9b3deab657f6788f9146191

###
POST http://localhost:4000/transactions

{
    "to":"nobod",
    "amount":30
}

###
http://localhost:4000/mempool


###
POST http://localhost:4000/peers

{
    "address": "127.0.0.1",
    "port": "3000"
}

###
GET http://localhost:3000/peers


###
http://localhost:3000/mempool


###
POST http://localhost:3000/peers

{
    "address": "127.0.0.1",
    "port": "2000"
}


###
GET http://localhost:2000/peers

